source 'https://rubygems.org'
gem 'rspec'
gem 'nokogiri'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'haml'
gem 'sidekiq'
gem 'sinatra-flash'
gem 'actionmailer'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'sass'
gem 'compass'
gem 'susy'
group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-sidekiq' , github: 'seuros/capistrano-sidekiq'
  gem 'pry'
end
