test:
  from_email: 
development:
  from_email: 
  smtp_settings:
    user_name: 
    password: 
    address: 
    domain: 
    port: 
    authentication: cram_md5
    enable_starttls_auto: true
production:
  from_email: 
  smtp_settings:
    user_name: 
    password: 
    address: 
    domain: 
    port: 

